ssg: static
 
paths:
  uploads: assets/uploads
 
collections_config:
  pages:
    path: ""
    output: true
    filter:
      base: strict
    include:
      - index.html
    name: Pages
    icon: web
 
_editables:
  text:
    bold: true
    italic: true
    link: true
    removeformat: true
    undo: true
    redo: true
  block:
    bold: true
    italic: true
    link: true
    removeformat: true
    undo: true
    redo: true
 
timezone: America/Phoenix
 
